name: Deploy to Github Pages

on:
  push:
    branches: [main]  # 或者你的主分支名称
  pull_request:
    branches: [main]  # 或者你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache Hugo resources
        uses: actions/cache@v4
        env:
          cache-name: cache-hugo-resources
        with:
          path: resources
          key: ${{ env.cache-name }}

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.17.0"
      - run: go version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --gc

      - name: Add CNAME file
        run: echo "blog.ouraihub.com" > public/CNAME

      # 部署到不同的仓库 hugoflow.github.io
      - name: Deploy to GitHub Pages repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.PAT }}  # 需要设置部署密钥
          external_repository: hugoflow/hugoflow.github.io  # 目标仓库
          publish_branch: main  # 目标仓库的分支
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
          # 如果目标仓库是私有的，可能需要以下选项
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'

